first_name = input(' What is your first name? ')
last_name = input('What is your last name? ')
email_address = input('What is your email? ')
phone_no = input('Phone Number: ')
job_tittle = input('Job Tittle: ')
ID_no = input('ID Number')
hair = input('Hair: ')
birth = input('Birth month:' )
eye = input('Eye color:' )
training = input('Have you received your training? ')


print('Your ID Badge:')
print('-----------------------------------')
print(f'{last_name.upper()},  {first_name.capitalize()}')
print('House Cleaner')
print(f'ID: {ID_no}')
print()
print(email_address)
print(phone_no)
print()
print(f'Hair: {hair.capitalize()}   Eyes: {eye.capitalize()} ')
print(f'Month: {birth.capitalize()} Training: {training} ')
print('-----------------------------------')